### ISSUE TITLE
Core option request - Add spacing between the two screens.

### ISSUE THREAD

**Issue by almostalive** [libretro/desmume2015#19]
I think it would be nice to be able to add some black space in-between the two ds screens. It might make it feel more natural for some games since the screens are apart on the handheld. I don't know if normal desmume can do this or not. For a visual reference of what I'm asking for https://www.youtube.com/watch?v=xKo3yguZm_s how he has it setup on the side of the screen separated a bit. It looks more correct than being right next to each other. It would be even more awesome if that setup could be recreated but thats probably asking to much. I just figured I would mention this since desmume is getting some attention right now.

**Comment by GPDP2** [comment]
Screen gap has just been added as a core option. This issue can be closed.

**Comment by Awakened0** [comment]
I tried today's Win64 nightly build of the core and the option doesn't show up. Looks like it should be under frameskip in the core options from looking at the source, but I'm not seeing it.

**Comment by Tatsuya79** [comment]
Same here.
Win64, tried yesterday and today build, the option isn't here.

**Comment by JackosDev** [comment]
Weird. There must be a problem with the buildbot.
Anyways, here's a [link](http://www.mediafire.com/download/v2apbxo5k1u6dkv/desmume_libretro_screengap.dll) of the latest build, compiled it myself.

**Comment by Tatsuya79** [comment]
Thanks, it's working with your version.
The Buildbot is such a liar, giving us the old stuff labelled as new!

**Comment by Awakened0** [comment]
Yeah, I eventually noticed the filesizes were exactly the same for the 19 and 22 buildbot builds. Thanks for the updated build!
