### ISSUE TITLE
Increase Dead Zone for Analog Cursor Control

### ISSUE THREAD

**Issue by Awakened0** [libretro/desmume2015#2]
Most times when I move the touch screen cursor with the analog stick it keeps moving even when I let it go. I think it must be because the dead zone is really small, because I don't have that problem with analog control in Mupen, Mednafen or MAME. An increased default dead zone or an option to increase dead zone percentage like what was added to Mupen would be helpful.

**Comment by andres-asm** [comment]
I'll be adding this, core is unusable with an XBOX 360 controller

**Comment by andres-asm** [comment]
https://github.com/libretro/desmume/pull/7
added

**Comment by Awakened0** [comment]
It works perfectly!
