### ISSUE TITLE
Crash in x86 and armhf linux

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/desmume2015#20]
You can't load any rom in x86.

retroarch
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
Microphone successfully inited.
DeSmuME 0.9.11 svn0 x86-JIT NOSSE
terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc
Aborted

It's happening in standalone too, upstream problem? Just opening this report to not lost info about.

Ubuntu 14.10 x86
core 2 duo E7400
VGA compatible controller: Intel Corporation 82G33/G31 Express Integrated Graphics Controller (rev 0a)

**Comment by sergiobenrocha2** [comment]
I'm having this issue with odroid u3 too

RetroArch [WARN] :: gl_glsl_init :: [GL]: Stock GLSL shaders will be used.
Microphone successfully inited.
DeSmuME 0.9.11 svn0 ARM-JIT NOSSE
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

Lubuntu 14.04 armhf
Exynos4412 Prime Cortex-A9 Quad-core

**Comment by sergiobenrocha2** [comment]
If you compile with clang, you don't have this issue. But you have issue #21 in x86.

**Comment by BlackLotus** [comment]
Ok since I came across this bug as well I took a quick stab at it.
Seems like the error lies within src/gfx3d.*
Wrote it down on my todo list and will probably look at it at some point again.

**Comment by sergiobenrocha2** [comment]
Fixed in some backport.
