### ISSUE TITLE
Single Screen View Option and Toggle Screen Button

### ISSUE THREAD

**Issue by Awakened0** [libretro/desmume2015#3]
In stand-alone Desmume there is an option to display only a single screen and assign a button to toggle between them. It works well for many games where the second screen only displays a map or other information you only need to glance at from time to time. The toggle screen button could be assigned to L2 on the retropad for easy access since it's not used for anything currently.

**Comment by Oggom** [comment]
I'm not sure if it's worth a separate issue report, but having an option to max out one window and move the other one into a corner (keeping both aspect ratios) would be a good addition so you can have the main screen in fullscreen and the second one (usually a map) in a small corner.

**Comment by Awakened0** [comment]
That would be a good use of the black bar area. I'm not sure how filters would work with it though. You'd probably want the small secondary screen unfiltered.

**Comment by andres-asm** [comment]
I'm gonna be looking into this now, if it's just desmume options I might be able to accomplish this

**Comment by andres-asm** [comment]
It's been addressed
https://github.com/libretro/desmume/commit/20684a5d53a9065ac03c39d9a578d0af392b7c1d
Please test it and let me know if anything is broken

**Comment by Awakened0** [comment]
Thanks, it works really well! The only small thing off is if you start RetroArch with the screen layout in quick swap or top or bottom screen only, if you try to switch to top+bottom or bottom+top you get a black screen until you switch it back to quick swap or top or bottom screen only, or restart RetroArch. If you start in top+bottom or bottom+top mode you can switch to any of the single screen modes without a problem.

**Comment by andres-asm** [comment]
wow that's weird and yeah I was able to reproduce..
I'm confused but I'll look into it.

I guess I'm not initializing something correctly

**Comment by andres-asm** [comment]
I fixed it, doing some extra stuff so I'll commit this later

**Comment by andres-asm** [comment]
fixed now
https://github.com/libretro/desmume/pull/7

**Comment by Awakened0** [comment]
Confirmed!
