### ISSUE TITLE
Pixel artifacts in 1/16/15 build and after

### ISSUE THREAD

**Issue by Awakened0** [libretro/desmume2015#34]
Seems like something went wrong after the new core options were added. I have a build from 1/15/15 that doesn't have the issue. I tried fiddling with the new options, but nothing seems to fix it. Super Princess Peach is the game I noticed it on, but others might be affected.

1/15/15 Build:
![15](https://cloud.githubusercontent.com/assets/4565863/5790436/1ffbdff6-9e66-11e4-9d09-55e69c9727f7.png)

1/16/15 Build (looks the same in 1/17/15 build too):
![16](https://cloud.githubusercontent.com/assets/4565863/5790437/34bd49fc-9e66-11e4-8a84-cbd23856e96c.png)

Some of the UI elements are a pixel to the left compared to the 1/15/15 build too.

**Comment by inactive123** [comment]
It's probably this commit -

https://github.com/libretro/desmume/commit/5e118e363067fa43f8bb5c54d2dac96abfd90eff

It fixed some Pokemon games but apparently caused many regressions in other games.

I'm reverting that patch for now.

**Comment by Awakened0** [comment]
That makes sense. Thanks for the quick response!

**Comment by Awakened0** [comment]
Tested a 1/18/15 build and it is indeed fixed.
