### ISSUE TITLE
X432R as a new core/branch?

### ISSUE THREAD

**Issue by JackosDev** [libretro/desmume2015#37]
The addition of X432R made the current code messy.
Also, would be easier to work on it without worrying of breaking the emulator.

**Comment by inactive123** [comment]
OK, we'll go with a new core then. I'll make a new repo for you without the X432R code, leave this a shallow fork, and give you commit access to the new one.

Sounds good?

**Comment by JackosDev** [comment]
Sure. Do as you think is better.

**Comment by inactive123** [comment]
OK, made the new repo and invited you.

I'll now roll back the X432R patches in this repo. The desmume-x432r repo will keep those.
