### ISSUE TITLE
validToProcessInput assertion failure crash

### ISSUE THREAD

**Issue by duganchen** [libretro/desmume2015#47]
I just built the Desmume core on Linux. When I launch a ROM, RetroArch crashes after half a second with the following in the terminal:

```
Microphone successfully inited.
DeSmuME 0.9.11 svn0 x64-JIT
Attempting change to 3d core to: SoftRasterizer
SoftRast Initialized with cores=1
RetroArch [WARN] :: rarch_log_libretro :: [libretro WARN] :: Save directory is not defined. Fallback on  using SYSTEM directory ...

ROM game code: YKWE
ROM serial: NTR-YKWE-USA
ROM chipID: 00007FC2
ROM internal name: KIRBY USDX E
ROM developer: Nintendo

Slot1 auto-selected device type: Retail MC+ROM
Slot2 auto-selected device type: None (0xFF)
DeSmuME .dsv save file not found. Trying to load an old raw .sav file.
CPU mode: JIT
JIT: max block size 100 instruction(s)
Already decrypted.
Autodetecting with autodetect_size=3
fish: Job 1, “retroarch” terminated by signal SIGSEGV (Address boundary error)
```

Tried two different ROMs, got the Address Boundary Error each time.

**Comment by duganchen** [comment]
I don't know how to build RetroArch with gdb debugging symbols. If you could tell me how to do that, then I'd be happy to do so and get more information.

**Comment by inactive123** [comment]
It should suffice to simply pass DEBUG=1 to make when compiling RetroArch.

**Comment by duganchen** [comment]
Here's the backtrace. With debugging symbols in both RetroArch and the desmume core.

http://pastebin.com/s4ZFBnE0

Please let me know if you'd like me to collect more information.

**Comment by duganchen** [comment]
Today I tried new builds of RetroArch and the DesMuMe ore, both from the current masters. The problem seems to have gone away.
