### ISSUE TITLE
add feature: change internal resolution

### ISSUE THREAD

**Issue by phly95** [libretro/desmume2015#49]
sure the main desmume build doesn't support higher internal resolution, but I don't believe there's anything preventing doing so on the libretro build.

**Comment by andres-asm** [comment]
The X432R fork is a mess, we already tried it's not a small patch or anything, it's very complicated.
We would like this too but hands are busy at other things.

**Comment by phly95** [comment]
Ah, well, I'm sure metroid prime hunters would be great once this feature is eventually added.

**Comment by phly95** [comment]
unfortunately due to the lack of anti-aliasing, prime hunters does not look good with super xbr due to it's reliance on antialiasing, but Desmume already supports anti-aliasing if it's on OpenGL mode, so do you think you can enable that so the SuperXBR filter can do its job?

**Comment by andres-asm** [comment]
no, the opengl renderer is not implemented

**Comment by inactive123** [comment]
Should be possible as of this commit - 

https://github.com/libretro/desmume/commit/5e430dfbc22f9d54c77f291304a38352ee1e5a63

I will add libretro GL support soon as well.
