### ISSUE TITLE
Sound quality regression

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/desmume2015#60]
Since the SPU rewrite that happened around the 9th of August, the sound quality is now quite worse.

I took some samples here: http://libretro.com/forums/showthread.php?t=4076
(Mario Kart, win7 x64)

**Comment by inactive123** [comment]
It's not worse, it's how the DS sounds like. I simply took out SPU Interpolation and all of the other nonsense that was in that horrible upstream implementation of audio.

The old code is not coming back, it is disastrously bad code. If you want better audio quality, it will have to be done through some other means, maybe one of our builtin resamplers that we integrate in the core, but I'm not going to settle for bringing back that old code again.
