### ISSUE TITLE
Nds games crashing the core

### ISSUE THREAD

**Issue by i30817** [libretro/desmume2015#97]
*most* games i tried on the same device crash now, and this seems to have started recently.
What seems to be common is a line 'Autodetecting with autodetect_size=3' on those that crash. Trace Memory (USA) is not crashing for example, and doesn't have the line.
This line exists on the file ./desmume/src/mc.cpp (memory card) on the desmume core source.

A example from order of ecclesia
Normal output before crash:

> i30817@AIVAS:~$ retroarch 
> DeSmuME 0.9.11 svn0 x64 NOSSE
> Attempting change to 3d core to: SoftRasterizer
> SoftRast Initialized with cores=1
> 
> Slot1 auto-selected device type: Retail MC+ROM
> Slot2 auto-selected device type: None (0xFF)
> DeSmuME .dsv save file not found. Trying to load an old raw .sav file.
> CPU mode: JIT
> JIT: max block size 12 instruction(s)
> Already decrypted.
> Autodetecting with autodetect_size=3
> Segmentation fault (core dumped)
> 

The path is fairly long, but not outlandish:
/media/i30817/Games/Nintendo DS/Castlevania - Order of Ecclesia (Europe) (En,Fr,De,Es,It)/Castlevania - Order of Ecclesia (Europe) (En,Fr,De,Es,It).nds

Finding the 'Ecclesia' lines with strace -o debug.txt -f -e trace=open  retroarch
showed me the file was found correctly, but saves weren't:

> 
> 24755 open("/media/i30817/Games/Nintendo DS/Castlevania - Order of Ecclesia (Europe) (En,Fr,De,Es,It)/Castlevania - Order of Ecclesia (Europe) (En,Fr,De,Es,It).nds", O_RDONLY) = 4
> 24755 open("desmume.ddb", O_RDONLY)     = -1 ENOENT (No such file or directory)
> 24755 open("/media/i30817/Games/Nintendo DS/Castlevania - Order of Ecclesia (Europe) (En,Fr,De,Es,It)/Castlevania - Order of Ecclesia (Europe) (En,Fr,De,Es,It).sav", O_RDONLY) = -1 ENOENT (No such file or directory)
> 24755 open("/media/i30817/Games/Nintendo DS/Castlevania - Order of Ecclesia (Europe) (En,Fr,De,Es,It)/Castlevania - Order of Ecclesia (Europe) (En,Fr,De,Es,It).dsv", O_RDWR|O_CREAT|O_TRUNC, 0666) = -1 EROFS (Read-only file system)
> 

(contrary to what may appear, i'm dead certain that the .dsv file it tried to open doesn't exist, just like the .sav file. There is no file except the nds rom in that dir).

Searching for '.dsv' shows that desmume crashed before it tried to open the preexisting dsv file of the game (that worked on previous versions) that exists on "/home/i30817/.config/retroarch/saves/Castlevania - Order of Ecclesia (Europe) (En,Fr,De,Es,It).dsv". The only lines with '.sav' or '.dsv' on the strace file are those shown here.
 (if that helps or is relevant).

Last few lines of strace before the crash appear unimportant:

> 24755 open("/home/i30817/.config/retroarch/content_music_history.lpl", O_RDONLY) = 19
> 24755 open("/home/i30817/.config/retroarch/content_video_history.lpl", O_RDONLY) = 19
> 24755 open("/home/i30817/.config/retroarch/content_image_history.lpl", O_RDONLY) = 19
> 24755 open("custom.ini", O_RDONLY)      = -1 ENOENT (No such file or directory)
> 24755 open("/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 19
> 24755 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
> 24766 +++ killed by SIGSEGV (core dumped) +++
> 24765 +++ killed by SIGSEGV (core dumped) +++
> 24764 +++ killed by SIGSEGV (core dumped) +++
> 24755 +++ killed by SIGSEGV (core dumped) +++

couldn't compile the desmume core using `DEBUG=1 NOCLEAN=1 ./libretro-build.sh desmume` since it fails at building with a lot of versions of this on debug:

> src/debug.cpp:227:4: error: invalid use of incomplete type ‘class EMUFILE’

and a lot of undefined references in the nondebug version, for example:

> /media/i30817/Huggin/Documents/projects/libretro-super/libretro-desmume/desmume/src/MMU_timing.h:330: undefined reference to `DebugEventData'

The normal gdb on the ppa core only shows that the SIGSEGV originates in a `fseek.c: No such file or directory`. but completely and utterly useless for debugging, since filenames and positions of functions calls are lost on the libretro desmume core on the testing ppa which i'm using.

**Comment by i30817** [comment]
BTW, the games are on a read-only volume.

**Comment by hizzlekizzle** [comment]
I believe the autodetecting part is referring to the type of storage it uses for saves.

You say this started fairly recently? Could you try to bisect/pinpoint when it started?

**Comment by i30817** [comment]
I _thought_ it was only happening recently, but meanwhile i installed the stable version instead of the unstable to check it out and it's the same. Only a few games, presumably the ones not trying to create the save file right away are starting. 
The old save must be from before i created the squash file, when i was using the external hdd.

I suspect it's the read-only dir that contains the rom files causing this, which is strange because the core should be placing them on ~/.config/retroarch/saves ; not trying on the ROM dir and bugging out when it's read only (at least have a fallback).

This is not the only affected core, ppsspp is also misbehaving (though upstream standalone isn't).

**Comment by i30817** [comment]
You can test this pretty easily by creating a read only dir with a nds file of a game that tries to create a .dsv file right away.

Read-only dir crashes, read write dir doesn't. And it actually writes a dsv file there now that i tested it ugh (stable libretro ppa).

**Comment by i30817** [comment]
This is a false alarm, i deleted the retroarch.cfg file when testing another bug, and the save dir config was nuked and defaulted to 'content dir'.
